COLOS-12: Initial codegen implementation
42dotmk/colosseum pull request #12
Opened 2024-02-06 18:32 UTC by gjorgi-krenkov

## Issue ID

## What has been done?

 - Integrated Senatus with client
 - Provided query hook "framework" example
 - Implemented `useGetAllEvents` query and represented the first event on the page.
 
## Sceenshots/Videos

![image](https://github.com/42dotmk/colosseum/assets/108683618/b8773b10-92bb-4e9c-bb69-58717b6b9bc7)

2024-02-13 15:23 UTC, iboshkov requested changes

2024-02-13 15:23 UTC, iboshkov commented on senatus/package.json
> +    "sqlite3": "^5.1.7",
We don't really need this as a dependency, we have a docker setup ready to go for local development that mirrors production.

2024-02-20 18:22 UTC, VasilakiG approved these changes

2024-02-20 18:37 UTC, iboshkov approved these changes

2024-02-20 18:37 UTC, merged