Create pull_request_template.md
42dotmk/colosseum pull request #7
Opened 2024-01-17 14:39 UTC by MarioStojcevski

2024-01-19 14:41 UTC, gjorgi-krenkov reviewed
Let's add fields in our template for a link to the Plane issue, and video/image request

2024-01-19 16:45 UTC, vergjor commented
> Let's add fields in our template for a link to the Plane issue, and video/image request

@MarioStojcevski you could potentially add something like this so that we don't have an empty template:

```markdown

## Issue ID

<!--Add issue link-->

## What has been done?

 - [ ] 

## Sceenshots/Videos

<!--Add screenshots or videos of the current task-->
```

2024-01-19 16:45 UTC, vergjor requested changes
> Let's add fields in our template for a link to the Plane issue, and video/image request

@MarioStojcevski you could potentially add something like this so that we don't have an empty template:

```markdown

## Issue ID

<!--Add issue link-->

## What has been done?

 - [ ] 

## Sceenshots/Videos

<!--Add screenshots or videos of the current task-->
```

2024-02-06 17:06 UTC, gjorgi-krenkov approved these changes

2024-02-06 17:06 UTC, vergjor approved these changes

2024-02-06 17:06 UTC, merged